version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    depends_on:
      - app
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"

volumes:
  db_data:
